### ISSUE TITLE
Update to Smack 4.1

### ISSUE THREAD

**Issue by Flowdalic** [Tibo-lg/HTTPoverXMPP#1]
I see that you bumped Smack to 3.2.1 in https://github.com/Tibo-lg/HTTPoverXMPP/commit/43bb06831b6002e2ce14fe9fbbe76195b3019a08. Not sure if this was a reaction to http://mail.jabber.org/pipermail/standards/2015-June/029900.html, but this is still an outdated and vulnerable Smack version. You should switch to Smack 4.1.1 (or higher), and use the Smack provided HTTP over XMPP API where possible.

**Comment by Tibo-lg** [comment]
Thank you for your message. I have switched to 3.2.1 for now but I am working on updating to 4.1.1 and using the HOXT library as much as possible. It takes a bit more time because I have to handle the server certificate, and find a good way to do that in my library. I'll update you when I'll be done, I'd be interested in your opinion with regards to some feature I implement.

And thank you for your work on Smack, I can see it improved a lot

**Comment by Tibo-lg** [comment]
I have updated to 4.1.1 and use the hoxt api. I basically just have a wrapper for hoxt now. 

I just have one small issue if I may ask your help. Looking at the debug output I noticed that Smack sends back an error when sending an hoxt message. Here is an example, this is the client output:

```
08:18:10 PM SENT (0): <iq to='test-server@service/t' id='1' type='set'><req xmlns='urn:xmpp:http' method='POST' resource='/test' version='1.1' sipub='true' ibb='true' jingle='true'><headers xmlns='http://jabber.org/protocol/shim'><header name='Content-Type'>application/text</header></headers><data><text>Hello server! Can I get my object?</text></data></req></iq>
08:18:10 PM RECV (0): <
08:18:10 PM RECV (0): iq to="test-client@service/t" id="1" type="error" from="test-server@service/t"><error type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
08:18:11 PM RECV (0): <
08:18:11 PM RECV (0): iq to="test-client@service/t" id="1" type="get" from="test-server@service/t"><resp xmlns="urn:xmpp:http" version="1.1" statusCode="200"><headers xmlns="http://jabber.org/protocol/shim"><header name="Host">test.com</header></headers><data><text>Sure it's at /test/myobject</text></data></resp></iq>
08:18:11 PM SENT (0): <iq to='test-server@service/t' id='1' type='error'><error type='cancel'><feature-not-implemented xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
```

Any idea why that happens?

**Comment by Flowdalic** [comment]
> Any idea why that happens?

Starting with Smack 4.1, you need to use and register a IQ request handler if you want to handle IQ requests. See existing code for examples.

**Comment by Tibo-lg** [comment]
Thank you! I updated to use IQRequestHandlers.
